import EventCategory from '../../../entities/EventCategory';
import CustomError from '../../../entities/CustomError';
import Page from '../../../entities/Page';
/**
 * Action types
 */

// eslint-disable-next-line no-shadow
export enum EventCategoryTypes {
  LIST_EVENT_CATEGORY_REQUEST = '@event-category/LIST_EVENT_CATEGORY_REQUEST',
  LIST_EVENT_CATEGORY_SUCCCES = '@company/LIST_EVENT_CATEGORY_SUCCCES',
  LIST_EVENT_CATEGORY_FAILURE = '@company/LIST_EVENT_CATEGORY_FAILURE',
  LIST_EVENT_CATEGORY_CLEAR = '@company/LIST_EVENT_CATEGORY_CLEAR',
  GET_ALL_EVENT_CATEGORY_REQUEST = '@company/GET_ALL_EVENT_CATEGORY_REQUEST',
  GET_ALL_EVENT_CATEGORY_SUCCCES = '@company/GET_EVENT_CATEGORY_SUCCCES',
  GET_ALL_EVENT_CATEGORY_FAILURE = '@company/GET_EVENT_CATEGORY_FAILURE',
  GET_EVENT_CATEGORY_REQUEST = '@company/GET_EVENT_CATEGORY_REQUEST',
  GET_EVENT_CATEGORY_SUCCCES = '@company/GET_EVENT_CATEGORY_SUCCCES',
  GET_EVENT_CATEGORY_FAILURE = '@company/GET_EVENT_CATEGORY_FAILURE',
  GET_EVENT_CATEGORY_CLEAR = '@company/GET_EVENT_CATEGORY_CLEAR',
  CREATE_EVENT_CATEGORY_REQUEST = '@company/CREATE_EVENT_CATEGORY_REQUEST',
  CREATE_EVENT_CATEGORY_SUCCCES = '@company/CREATE_EVENT_CATEGORY_SUCCCES',
  CREATE_EVENT_CATEGORY_FAILURE = '@company/CREATE_EVENT_CATEGORY_FAILURE',
  UPDATE_EVENT_CATEGORY_REQUEST = '@company/UPDATE_EVENT_CATEGORY_REQUEST',
  UPDATE_EVENT_CATEGORY_SUCCCES = '@company/UPDATE_EVENT_CATEGORY_SUCCCES',
  UPDATE_EVENT_CATEGORY_FAILURE = '@company/UPDATE_EVENT_CATEGORY_FAILURE',
  ACTIVATE_EVENT_CATEGORY_REQUEST = '@company/ACTIVATE_EVENT_CATEGORY_REQUEST',
  ACTIVATE_EVENT_CATEGORY_SUCCCES = '@company/ACTIVATE_EVENT_CATEGORY_SUCCCES',
  ACTIVATE_EVENT_CATEGORY_FAILURE = '@company/ACTIVATE_EVENT_CATEGORY_FAILURE',
  INACTIVATE_EVENT_CATEGORY_REQUEST = '@company/INACTIVATE_EVENT_CATEGORY_REQUEST',
  INACTIVATE_EVENT_CATEGORY_SUCCCES = '@company/INACTIVATEEVENT_CATEGORY_SUCCCES',
  INACTIVATE_EVENT_CATEGORY_FAILURE = '@company/INACTIVATE_EVENT_CATEGORY_FAILURE',
  DELETE_EVENT_CATEGORY_REQUEST = '@company/DELETE_EVENT_CATEGORY_REQUEST',
  DELETE_EVENT_CATEGORY_SUCCCES = '@company/DELETE_EVENT_CATEGORY_SUCCCES',
  DELETE_EVENT_CATEGORY_FAILURE = '@company/DELETE_EVENT_CATEGORY_FAILURE',
}

/**
 * Data types
 */

export interface EventCategoryDataType {
  page: Page<EventCategory, EventCategory>;
  entity: EventCategory;
  list: EventCategory[];
}

/**
 * State type
 */
export interface EventCategoryState {
  readonly data: EventCategoryDataType;
  readonly loading: boolean;
  readonly error: CustomError | undefined;
}
