name: CI
on:
  push:
    branches:
      - develop

jobs:
  deploy-prd:
    name: Deploy - DEV
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Writing .env file
        run: 'echo "${{ secrets.ENVIRONMENT_VARIABLES_DEV }}" > .env'
      
      - name: Install dependencies
        run: yarn

      - name: Updating the caniuse-lite database with browsers
        run: npx browserslist@latest --update-db

      - name: Build app
        run: yarn build
        env:
          CI: ''

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: us-east-1

      - name: Deploy to S3
        run: aws s3 sync . s3://dev-bdi-adm/
        working-directory: ./build